import { notFound } from "next/navigation";
import Link from "next/link";
import type { Metadata } from "next";
import { Sparkle, CheckCircle, Warning, Bookmark, Phone, ArrowLeft, Tag } from "@phosphor-icons/react/dist/ssr";
import { Navigation } from "@/components/navigation";
import { Footer } from "@/components/footer";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Breadcrumbs } from "@/components/seo/breadcrumbs";
import { DefinedTermSchema } from "@/components/seo/extended-schemas";
import { FAQSchema } from "@/components/seo/structured-data";

interface TermDetail {
  slug: string;
  name: string;
  category: string;
  definition: string;
  whyItMatters: string;
  countryApplicability: string;
  commonMistakes: string[];
  relatedEntities: { name: string; url: string }[];
  faqs: { question: string; answer: string }[];
}

const termsDataMap: Record<string, TermDetail> = {
  cas: {
    slug: "cas",
    name: "CAS (Confirmation of Acceptance for Studies)",
    category: "United Kingdom",
    definition: "A CAS (Confirmation of Acceptance for Studies) is a unique 14-digit electronic reference number generated by UK licensed universities through the UK Home Office portal. It confirms that the university has offered you an unconditional place and agrees to sponsor your UK Student Visa.",
    whyItMatters: "Without a valid CAS, you cannot lodge a UK Student Visa application. The CAS contains vital information including your course tuition fees, deposit payments, English language proficiency proof, and academic qualification verification.",
    countryApplicability: "United Kingdom",
    commonMistakes: [
      "Submitting visa application before receiving the official CAS email",
      "Using an expired CAS (valid for 6 months from issue date)",
      "Discrepant passport details between CAS and visa application"
    ],
    relatedEntities: [
      { name: "Study in UK", url: "/study-abroad/uk" },
      { name: "Student Visa Guide", url: "/guides/student-visa-guide" },
      { name: "UCAS Application", url: "/glossary/ucas" }
    ],
    faqs: [
      { question: "How long does it take to receive a CAS letter?", answer: "Most UK universities issue a CAS within 5 to 10 working days after you pay your initial tuition deposit and upload financial proofing." }
    ]
  },
  gic: {
    slug: "gic",
    name: "GIC (Guaranteed Investment Certificate)",
    category: "Canada",
    definition: "A GIC (Guaranteed Investment Certificate) is a mandatory financial investment (CAD $20,635) deposited into a designated Canadian bank (e.g. Scotiabank, CIBC) by international students applying for a Canadian Study Permit under the Student Direct Stream (SDS).",
    whyItMatters: "The GIC serves as indisputable proof to Immigration, Refugees and Citizenship Canada (IRCC) that you have adequate living expense funds for your first year in Canada. Upon arrival, CAD $2,000+ is released immediately, with monthly installments paid over 12 months.",
    countryApplicability: "Canada",
    commonMistakes: [
      "Depositing funds into an unapproved non-Canadian financial institution",
      "Failing to upload the official GIC Attestation Letter to IRCC",
      "Transferring funds from a third-party unverified bank account"
    ],
    relatedEntities: [
      { name: "Study in Canada", url: "/study-abroad/canada" },
      { name: "PGWP Work Permit", url: "/glossary/pgwp" },
      { name: "Student Direct Stream (SDS)", url: "/glossary/sds" }
    ],
    faqs: [
      { question: "Can GIC funds be refunded if my Canada visa is rejected?", answer: "Yes! If your Study Permit is refused, the Canadian bank will refund the full GIC amount back to your original bank account minus minor wire fees." }
    ]
  },
  pgwp: {
    slug: "pgwp",
    name: "PGWP (Post-Graduation Work Permit)",
    category: "Canada",
    definition: "The Post-Graduation Work Permit (PGWP) is an open work visa granted to international graduates who complete an eligible degree, diploma, or certificate program at a Canadian Designated Learning Institution (DLI).",
    whyItMatters: "PGWP allows international graduates to gain valuable Canadian work experience without requiring a specific job offer. Work experience gained under PGWP contributes directly to permanent residency points under the Canadian Experience Class (CEC) of Express Entry.",
    countryApplicability: "Canada",
    commonMistakes: [
      "Applying after the 180-day deadline following official final marks",
      "Studying part-time during mandatory academic semesters",
      "Attending an ineligible non-DLI private college"
    ],
    relatedEntities: [
      { name: "Study in Canada", url: "/study-abroad/canada" },
      { name: "GIC Requirement", url: "/glossary/gic" },
      { name: "Canada vs Australia", url: "/compare/canada-vs-australia" }
    ],
    faqs: [
      { question: "How long is a PGWP valid?", answer: "Programs of 8 months to 2 years grant a PGWP equal to program length. Master's and 2+ year degree programs grant a 3-year PGWP." }
    ]
  },
  dsu: {
    slug: "dsu",
    name: "DSU Scholarship (Diritto allo Studio Universitario)",
    category: "Italy",
    definition: "The DSU Scholarship is a regional Italian government financial need grant awarded to eligible international students studying at public state universities in Italy based on family income evaluation (ISEE Parificato).",
    whyItMatters: "DSU covers 100% of state university tuition fees, grants free campus accommodation and daily canteen meals, and provides an annual cash stipend of up to €7,000.",
    countryApplicability: "Italy",
    commonMistakes: [
      "Submitting non-translated or un-apostilled family income certificates",
      "Missing the regional DSU deadline (typically August/September)",
      "Failing to maintain minimum annual academic credit passes (CFUs)"
    ],
    relatedEntities: [
      { name: "Study in Italy", url: "/study-abroad/italy" },
      { name: "Germany vs Italy", url: "/compare/germany-vs-italy" },
      { name: "Scholarship Guide", url: "/guides/scholarship-guide" }
    ],
    faqs: [
      { question: "Do I need high marks to win the Italian DSU scholarship?", answer: "No! First-year DSU eligibility is based primarily on family financial background, not high competitive entrance marks." }
    ]
  }
};

export async function generateStaticParams() {
  return [
    { term: "cas" },
    { term: "gic" },
    { term: "pgwp" },
    { term: "dsu" }
  ];
}

export async function generateMetadata({ params }: { params: Promise<{ term: string }> }): Promise<Metadata> {
  const resolved = await params;
  const termKey = (resolved?.term || "").toLowerCase();
  const data = termsDataMap[termKey];
  if (!data) return { title: "Term Not Found | Annex Consultancy" };

  return {
    title: `${data.name} Explained | Definition, Rules & Mistakes`,
    description: `Complete guide to ${data.name}. Learn the definition, why it matters, country rules, common mistakes, and related entities.`,
    alternates: {
      canonical: `https://annex-consultancy.com/glossary/${data.slug}`,
    },
  };
}

export default async function GlossaryTermPage({ params }: { params: Promise<{ term: string }> }) {
  const resolved = await params;
  const termKey = (resolved?.term || "").toLowerCase();
  const data = termsDataMap[termKey];
  if (!data) notFound();

  return (
    <>
      <DefinedTermSchema
        term={data.name}
        definition={data.definition}
        url={`https://annex-consultancy.com/glossary/${data.slug}`}
      />
      <FAQSchema faqs={data.faqs} />
      <Navigation />

      <main className="flex-grow pt-24 md:pt-28 bg-white">
        <Breadcrumbs
          items={[
            { name: "Glossary Hub", url: "https://annex-consultancy.com/glossary" },
            { name: data.name, url: `https://annex-consultancy.com/glossary/${data.slug}` }
          ]}
        />

        {/* HERO */}
        <section className="py-12 bg-white">
          <div className="max-w-7xl mx-auto px-6 lg:px-8 space-y-4">
            <div className="flex items-center gap-3">
              <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-subtle-gray border border-hairline text-xs font-bold uppercase tracking-wider text-primary">
                <Tag size={14} className="text-primary" /> {data.category}
              </span>
            </div>

            <h1 className="font-display font-bold text-4xl md:text-6xl text-primary tracking-tight">
              {data.name}
            </h1>

            <p className="text-base md:text-lg text-slate-700 font-medium max-w-3xl leading-relaxed">
              {data.definition}
            </p>
          </div>
        </section>

        {/* WHY IT MATTERS & COMMON MISTAKES */}
        <section className="py-12 bg-subtle-gray border-y border-hairline">
          <div className="max-w-7xl mx-auto px-6 lg:px-8 space-y-12">
            <Card className="p-8 border-hairline bg-white space-y-3">
              <h2 className="font-display font-bold text-2xl text-primary">Why {data.name} Matters</h2>
              <p className="text-slate-600 text-sm md:text-base leading-relaxed">{data.whyItMatters}</p>
            </Card>

            <Card className="p-8 border-hairline bg-white space-y-4">
              <h2 className="font-display font-bold text-2xl text-primary flex items-center gap-2">
                <Warning size={24} className="text-amber-500" /> Common Mistakes Students Make
              </h2>
              <ul className="space-y-2.5 text-xs md:text-sm text-slate-700 font-medium">
                {data.commonMistakes.map((m, i) => (
                  <li key={i} className="flex items-start gap-2.5">
                    <span className="w-1.5 h-1.5 rounded-full bg-amber-500 mt-2 shrink-0" />
                    <span>{m}</span>
                  </li>
                ))}
              </ul>
            </Card>
          </div>
        </section>

        {/* RELATED ENTITIES & FAQS */}
        <section className="py-16 bg-white">
          <div className="max-w-7xl mx-auto px-6 lg:px-8 space-y-12">
            <div className="space-y-4">
              <h2 className="font-display font-bold text-2xl text-primary">Connected Entities & Guides</h2>
              <div className="flex flex-wrap gap-3">
                {data.relatedEntities.map((ent, i) => (
                  <Link
                    key={i}
                    href={ent.url}
                    className="px-4 py-2 rounded-xl bg-subtle-gray hover:bg-slate-100 border border-hairline font-bold text-xs text-primary transition-colors"
                  >
                    {ent.name} →
                  </Link>
                ))}
              </div>
            </div>

            <div className="space-y-6 max-w-4xl">
              <h2 className="font-display font-bold text-2xl text-primary">Frequently Asked Questions</h2>
              <div className="space-y-4">
                {data.faqs.map((faq, i) => (
                  <div key={i} className="p-5 rounded-2xl border border-hairline bg-subtle-gray/30 space-y-2">
                    <h3 className="font-bold text-base text-primary">{faq.question}</h3>
                    <p className="text-xs md:text-sm text-slate-600 leading-relaxed">{faq.answer}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
